### ISSUE TITLE
一些问题请教大佬

### ISSUE THREAD

**Issue by dc-walker** [IshiKura-a/Quicker#6]
大佬这个报错是什么意思啊
2023-11-02 12:00:00,003 - INFO - Running job "job (trigger: interval[0:00:10], next run at: 2023-11-02 12:00:00 CST)" (scheduled at 2023-11-02 12:00:00+08:00)
2023-11-02 12:00:00,581 - INFO - 0 Login Success!
2023-11-02 12:00:02,387 - INFO - 0 Login Success!
2023-11-02 12:00:04,030 - INFO - buddy_no: 71167,71167
2023-11-02 12:00:07,214 - INFO - 0 Login Success!
2023-11-02 12:00:07,713 - INFO - [{"spaceId":"134","timeId":"6644","venueSpaceGroupId":null}]
2023-11-02 12:00:07,949 - INFO - Traceback (most recent call last):
  File "main.py", line 307, in exec
    result = self.order(buddy_no, reserver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 250, in order
    captcha_verification = self.solve_captcha(mode='clickWord')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 432, in solve_captcha
    point_arr = self.ocr_captcha(base64_img, word_list)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 341, in ocr_captcha
    det = ddddocr.DdddOcr(det=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DdddOcr.__init__() got an unexpected keyword argument 'det'

还有就是选的时间段从浙大体艺看还有场地但程序输出已经约满555
那个场地编号从哪里能看到啊，这里只知道玉泉的羽毛球场是39诶555

**Comment by IshiKura-a** [comment]
1. 针对`TypeError: DdddOcr.init() got an unexpected keyword argument 'det'`，这个是ddddocr的问题，他可能更新了相关的参数，导致了不兼容。
你可以：（1）使用指令`pip install ddddocr==1.4.7 --upgrade`调整到我的版本，或者（2）更新到最新版本去github对应仓库查看最新的使用方法
2. 关于如何查看场地id，可以参考https://github.com/IshiKura-a/Quicker/issues/1#issuecomment-921809188，需要一些前端知识，ctrl+shift+i（Mac为command+option+i）打开开发人员工具，切换到网络这个页面，抓取请求。
3. 如果上述问题解决了，仍然提示预约已满，可以贴一下具体预约的场次信息以及完整的报错信息

**Comment by dc-walker** [comment]
谢谢大佬！！！改了ddddocr的版本之后那个解决了然后场地id我也会查啦！但是现在又遇到
2023-11-02 22:31:15,402 - INFO - Namespace(input='./in.txt', mode='interval', start_time='2023-11-02 21:20:00')      
2023-11-02 22:31:15,418 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-11-02 22:31:15,419 - INFO - Added job "job" to job store "default"
2023-11-02 22:31:15,420 - INFO - Scheduler started
2023-11-02 22:31:20,015 - INFO - Running job "job (trigger: interval[0:00:10], next run at: 2023-11-02 22:31:20 CST)" (scheduled at 2023-11-02 22:31:20+08:00)
2023-11-02 22:31:20,685 - INFO - 0 Login Success!
2023-11-02 22:31:21,380 - INFO - 0 Login Success!
2023-11-02 22:31:21,436 - INFO - buddy_no: 71167,71167
2023-11-02 22:31:22,054 - INFO - 0 Login Success!
2023-11-02 22:31:22,221 - INFO - [{"spaceId":"144","timeId":"6723","venueSpaceGroupId":null}]
2023-11-02 22:31:22,647 - INFO - Traceback (most recent call last):
  File "main.py", line 307, in exec
    result = self.order(buddy_no, reserver)
  File "main.py", line 250, in order
    captcha_verification = self.solve_captcha(mode='clickWord')
  File "main.py", line 432, in solve_captcha
    point_arr = self.ocr_captcha(base64_img, word_list)
  File "main.py", line 360, in ocr_captcha
    res = ocr.classification(cropped_img)
  File "C:\Users\14022\.conda\envs\bad\lib\site-packages\ddddocr\__init__.py", line 1614, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
 我试着换了pillow的版本可有的版本会直接报错
 import ddddocr
  File "C:\Users\14022\.conda\envs\bad\lib\site-packages\ddddocr\__init__.py", line 11, in <module>
    from PIL import Image, ImageChops
ImportError: cannot import name 'Image' from 'PIL' (unknown location)
请问应该怎么解决哇

**Comment by dc-walker** [comment]
前面那个报错没贴全抱歉
File "C:\Users\14022\.conda\envs\bad\lib\site-packages\ddddocr\__init__.py", line 1614, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by dc-walker** [comment]
哦哦我解决啦是pillow版本在10.0以上取消了ANTIALIAS，改了版本之后已经可以运行啦。再次感谢大佬！！！！有点小问题就是同伴码那里获取到的是自己的同伴码，而约场地需要输入self.companion那里同伴的同伴码（两个不一样）。这里应该要改成用户输入这个同伴的同伴码而不是系统自动获取，大佬有时间的话可以改改嘻嘻

**Comment by dc-walker** [comment]
哦哦看懂了，我把同伴验证那里的学号密码也填成自己的了，是我蠢了呜呜。再次感谢前辈大佬的无私！！！！
