### ISSUE TITLE
有场地但是显示预约已满的问题

### ISSUE THREAD

**Issue by dc-walker** [IshiKura-a/Quicker#7]
- 大佬你好，又来请教了QAQ。就是前两天说的那个有场地但是会显示预约已满
<img width="959" alt="image" src="https://github.com/IshiKura-a/Quicker/assets/97432449/df2e59f7-1521-4311-b4ff-271e7bc6e1aa">
可以看到 `2023-11-05 7:30` 场地很充足但是：

```
2023-11-04 13:32:22,116 - INFO - -----------------
2023-11-04 13:32:22,119 - INFO - 场地编号: 23
2023-11-04 13:32:22,119 - INFO - 预约日期: 2023-11-05
2023-11-04 13:32:22,119 - INFO - 候选时间: ['2023-11-05 7:30']
2023-11-04 13:32:22,119 - INFO - 预约场数: 1
2023-11-04 13:32:22,119 - INFO - 同伴: ['xxx']
2023-11-04 13:32:22,119 - INFO - 手机号: xxx
2023-11-04 13:32:22,119 - INFO - -----------------

2023-11-04 13:32:22,119 - INFO - Namespace(input='./in.txt', mode='interval', start_time='2023-11-04 13:32:40')
2023-11-04 13:32:22,131 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2023-11-04 13:32:22,135 - INFO - Added job "job" to job store "default"
2023-11-04 13:32:22,135 - INFO - Scheduler started
2023-11-04 13:32:40,001 - INFO - Running job "job (trigger: interval[0:00:10], next run at: 2023-11-04 13:32:40 CST)" (scheduled at 2023-11-04 13:32:40+08:00)
2023-11-04 13:32:40,786 - INFO - 321010xxxx Login Success!
2023-11-04 13:32:40,854 - INFO - buddy_no: 12949
2023-11-04 13:32:41,652 - INFO - 321010xxxx Login Success!
2023-11-04 13:32:42,048 - CRITICAL - 所有场次均被预约
2023-11-04 13:32:42,051 - INFO - Job "job (trigger: interval[0:00:10], next run at: 2023-11-04 13:32:50 CST)" executed successfully 
Traceback (most recent call last):
  File "main.py", line 528, in <module>
    main()
  File "main.py", line 517, in main
    schedule.start()
  File "C:\Users\14022\.conda\envs\bad\lib\site-packages\apscheduler\schedulers\blocking.py", line 21, in start
    self._main_loop()
  File "C:\Users\14022\.conda\envs\bad\lib\site-packages\apscheduler\schedulers\blocking.py", line 30, in _main_loop
    self._event.wait(wait_seconds)
  File "C:\Users\14022\.conda\envs\bad\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\14022\.conda\envs\bad\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
```

- 还有一个问题就是大佬有没有考虑加一个优先选择某一片场地的功能哇，我看choose_space那里好像是直接顺序遍历的但是我不太懂python所以不太敢改

**Comment by IshiKura-a** [comment]
1. 下次触发此问题时，请提供`choose_space`函数的输入`input`，如果可以的话，打断点查看`if key.isnumeric() and value["reservationStatus"] == 1 and value["startDate"] in reserver.candidate`此条件是否正确触发。
2. 如要优先选择某场地，需要预先知道对应场地的`spaceId`，如果发现场地空闲，直接返回对应的json参数。

**Comment by dc-walker** [comment]
哦哦好的，想问下这个是什么意思啊
```
2023-11-21 12:37:40,014 - WARNING - Execution of job "job (trigger: interval[0:00:10], next run at: 2023-11-21 12:37:40 CST)" skipped: maximum number of running instances reached (1)
```

**Comment by IshiKura-a** [comment]
意思是当前任务的执行时间超过了任务的执行间隔（这里是10s），所以本来是10s执行一次的任务，因为上一个任务还在执行而跳过了。
